version: '3.8'
services:
  stats-server:
    build: ./stats-service/stat-server
    image: ewn-stats-server-image
    container_name: ewm_stats
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
    - SPRING_DATASOURCE_USERNAME=postgres
    - SPRING_DATASOURCE_PASSWORD=Zaven2904
    - SERVER_PORT=9090

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Zaven2904
    volumes:
      - /var/lib/postgresql/data/

  ewm-service:
    build: ./main-service
    image: ewn-main-service-image
    container_name: ewm_main
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - STAT_SERVER_URL=http://stats-server:9090
      - MAIN_SERVICE_PORT=8080
      - URL=jdbc:postgresql://ewm-db:5432/ewn-db
      - USERNAME=postgres
      - PASSWORD=Zaven2904

  ewm-db:
    image: postgres:14-alpine

    container_name: ewm-db-container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewn-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Zaven2904
    volumes:
      - /var/lib/postgresql/data/

